spring:
  application:
    name: dataflux
  r2dbc:
    url: r2dbc:mysql://localhost:3306/dataflux?sslMode=DISABLED
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0