server:
  port: 9090
spring:
  application:
    name: dataflux
  r2dbc:
    url: r2dbc:mysql://localhost:3306/dataflux?sslMode=DISABLED
    username: root
    password: P@88w0rd
  redis:
    host: localhost
    port: 6379
    password: P@88w0rd
    database: 0